version: '3.8'

services:
  chat-web:
    image: apconw/chat-vue3-mvp:1.1.5
    container_name: chat-vue3-mvp
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8081:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - chat-service

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    ports:
      - "19000:9000"
      - "19001:9001"
    volumes:
      - ./volume/minio/data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=12345678
    command: server /data --console-address ":9001"

  chat-service:
    image: apconw/sanic-web:1.1.5
    container_name: sanic-web
    environment:
      - ENV=test
      - DIFY_SERVER_URL=http://host.docker.internal:18000
      - DIFY_DATABASE_QA_API_KEY=app-GIz9dM9GPUXVZOkDRaC0TOxh
      - MINIO_ENDPOINT=host.docker.internal:19000
      - MINIO_ACCESS_KEY=QfIx8FgdpgKtmbFMbKVb
      - MiNIO_SECRET_KEY=DsitWZJT3pecrg020Y2NKCETVpsIc3h2PrKTqONA
      - MODEL_BASE_URL=https://dashscope.aliyuncs.com/compatible-mode/v1
      - MODEL_NAME=qwen-plus
      - MODEL_TEMPERATURE=0.75
      - MODEL_API_KEY=sk-xxx
      - MCP_HUB_URL=http://host.docker.internal:3300/mcp
      - TZ=Asia/Shanghai
    ports:
      - "8088:8088"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    image: mysql:latest
    container_name: chat-db
    ports:
      - "13006:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1
      - CHARACTER_SET_SERVER=utf8mb4
      - COLLATION_SERVER=utf8mb4_unicode_ci
      - TZ=Asia/Shanghai
    volumes:
      - ./volume/mysql/data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

  mcphub:
    image: samanhappy/mcphub
    container_name: mcphub
    ports:
      - "3300:3000"
    volumes:
      - ./volume/mcp-data/mcp_settings.json:/app/mcp_settings.json
      - ./volume/mcp-data/data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
