version: '3.8'

services:
  chat-web:
    image: apconw/chat-vue3-mvp:1.0
    container_name: chat-vue3-mvp
    ports:
      - "8081:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - chat-service
    networks:
      - dify_service_default

  chat-service:
    image: apconw/sanic-web:1.0
    container_name: sanic-web
    ports:
      - "8088:8088"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - dify_service_default

  mysql:
    image: mysql:latest
    container_name: chat-db
    ports:
      - "13006:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1
      - CHARACTER_SET_SERVER=utf8mb4
      - COLLATION_SERVER=utf8mb4_unicode_ci
    volumes:
      - ./volume/mysql/data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - dify_service_default

# dify_service_default网络第一步安装内置Dify自动创建的
networks:
  dify_service_default:
    external: true
    driver: bridge